# Generated by Django 2.0.6 on 2018-06-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('HAP', 'Happy mood'), ('SAD', 'Sad mood'), ('ANG', 'Angry mood'), ('COO', 'Cool mood')], default='HAP', max_length=3)),
                ('text', models.TextField()),
            ],
        ),
    ]
